name: 'Create Docker Manifest'
description: 'Creates a Docker Manifest for the given set of images'
inputs:
  images:  # set of images to create manifest for
    description: 'Set of images to create manifest for'
    required: true
  manifest:  # the name of the manifest to create
    description: 'The name of the manifest to create'
    required: true
  push:
    description: 'Push the manifest to the registry'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.images }}
    - ${{ inputs.manifest }}
    - ${{ inputs.push }}
